/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SalaryService } from "../salary.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SalaryCreateInput } from "./SalaryCreateInput";
import { Salary } from "./Salary";
import { SalaryFindManyArgs } from "./SalaryFindManyArgs";
import { SalaryWhereUniqueInput } from "./SalaryWhereUniqueInput";
import { SalaryUpdateInput } from "./SalaryUpdateInput";
import { PayslipFindManyArgs } from "../../payslip/base/PayslipFindManyArgs";
import { Payslip } from "../../payslip/base/Payslip";
import { PayslipWhereUniqueInput } from "../../payslip/base/PayslipWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SalaryControllerBase {
  constructor(
    protected readonly service: SalaryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Salary })
  @nestAccessControl.UseRoles({
    resource: "Salary",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSalary(@common.Body() data: SalaryCreateInput): Promise<Salary> {
    return await this.service.createSalary({
      data: {
        ...data,

        employee: data.employee
          ? {
              connect: data.employee,
            }
          : undefined,
      },
      select: {
        allowances: true,
        basic: true,
        createdAt: true,
        deductions: true,

        employee: {
          select: {
            id: true,
          },
        },

        id: true,
        netPay: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Salary] })
  @ApiNestedQuery(SalaryFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Salary",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async salaries(@common.Req() request: Request): Promise<Salary[]> {
    const args = plainToClass(SalaryFindManyArgs, request.query);
    return this.service.salaries({
      ...args,
      select: {
        allowances: true,
        basic: true,
        createdAt: true,
        deductions: true,

        employee: {
          select: {
            id: true,
          },
        },

        id: true,
        netPay: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Salary })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Salary",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async salary(
    @common.Param() params: SalaryWhereUniqueInput
  ): Promise<Salary | null> {
    const result = await this.service.salary({
      where: params,
      select: {
        allowances: true,
        basic: true,
        createdAt: true,
        deductions: true,

        employee: {
          select: {
            id: true,
          },
        },

        id: true,
        netPay: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Salary })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Salary",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSalary(
    @common.Param() params: SalaryWhereUniqueInput,
    @common.Body() data: SalaryUpdateInput
  ): Promise<Salary | null> {
    try {
      return await this.service.updateSalary({
        where: params,
        data: {
          ...data,

          employee: data.employee
            ? {
                connect: data.employee,
              }
            : undefined,
        },
        select: {
          allowances: true,
          basic: true,
          createdAt: true,
          deductions: true,

          employee: {
            select: {
              id: true,
            },
          },

          id: true,
          netPay: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Salary })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Salary",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSalary(
    @common.Param() params: SalaryWhereUniqueInput
  ): Promise<Salary | null> {
    try {
      return await this.service.deleteSalary({
        where: params,
        select: {
          allowances: true,
          basic: true,
          createdAt: true,
          deductions: true,

          employee: {
            select: {
              id: true,
            },
          },

          id: true,
          netPay: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/payslips")
  @ApiNestedQuery(PayslipFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Payslip",
    action: "read",
    possession: "any",
  })
  async findPayslips(
    @common.Req() request: Request,
    @common.Param() params: SalaryWhereUniqueInput
  ): Promise<Payslip[]> {
    const query = plainToClass(PayslipFindManyArgs, request.query);
    const results = await this.service.findPayslips(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        issueDate: true,

        payroll: {
          select: {
            id: true,
          },
        },

        salary: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/payslips")
  @nestAccessControl.UseRoles({
    resource: "Salary",
    action: "update",
    possession: "any",
  })
  async connectPayslips(
    @common.Param() params: SalaryWhereUniqueInput,
    @common.Body() body: PayslipWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payslips: {
        connect: body,
      },
    };
    await this.service.updateSalary({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/payslips")
  @nestAccessControl.UseRoles({
    resource: "Salary",
    action: "update",
    possession: "any",
  })
  async updatePayslips(
    @common.Param() params: SalaryWhereUniqueInput,
    @common.Body() body: PayslipWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payslips: {
        set: body,
      },
    };
    await this.service.updateSalary({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/payslips")
  @nestAccessControl.UseRoles({
    resource: "Salary",
    action: "update",
    possession: "any",
  })
  async disconnectPayslips(
    @common.Param() params: SalaryWhereUniqueInput,
    @common.Body() body: PayslipWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payslips: {
        disconnect: body,
      },
    };
    await this.service.updateSalary({
      where: params,
      data,
      select: { id: true },
    });
  }
}
