/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PayslipService } from "../payslip.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PayslipCreateInput } from "./PayslipCreateInput";
import { Payslip } from "./Payslip";
import { PayslipFindManyArgs } from "./PayslipFindManyArgs";
import { PayslipWhereUniqueInput } from "./PayslipWhereUniqueInput";
import { PayslipUpdateInput } from "./PayslipUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PayslipControllerBase {
  constructor(
    protected readonly service: PayslipService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Payslip })
  @nestAccessControl.UseRoles({
    resource: "Payslip",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPayslip(
    @common.Body() data: PayslipCreateInput
  ): Promise<Payslip> {
    return await this.service.createPayslip({
      data: {
        ...data,

        payroll: data.payroll
          ? {
              connect: data.payroll,
            }
          : undefined,

        salary: data.salary
          ? {
              connect: data.salary,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        issueDate: true,

        payroll: {
          select: {
            id: true,
          },
        },

        salary: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Payslip] })
  @ApiNestedQuery(PayslipFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Payslip",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async payslips(@common.Req() request: Request): Promise<Payslip[]> {
    const args = plainToClass(PayslipFindManyArgs, request.query);
    return this.service.payslips({
      ...args,
      select: {
        createdAt: true,
        id: true,
        issueDate: true,

        payroll: {
          select: {
            id: true,
          },
        },

        salary: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Payslip })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Payslip",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async payslip(
    @common.Param() params: PayslipWhereUniqueInput
  ): Promise<Payslip | null> {
    const result = await this.service.payslip({
      where: params,
      select: {
        createdAt: true,
        id: true,
        issueDate: true,

        payroll: {
          select: {
            id: true,
          },
        },

        salary: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Payslip })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Payslip",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePayslip(
    @common.Param() params: PayslipWhereUniqueInput,
    @common.Body() data: PayslipUpdateInput
  ): Promise<Payslip | null> {
    try {
      return await this.service.updatePayslip({
        where: params,
        data: {
          ...data,

          payroll: data.payroll
            ? {
                connect: data.payroll,
              }
            : undefined,

          salary: data.salary
            ? {
                connect: data.salary,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          issueDate: true,

          payroll: {
            select: {
              id: true,
            },
          },

          salary: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Payslip })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Payslip",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePayslip(
    @common.Param() params: PayslipWhereUniqueInput
  ): Promise<Payslip | null> {
    try {
      return await this.service.deletePayslip({
        where: params,
        select: {
          createdAt: true,
          id: true,
          issueDate: true,

          payroll: {
            select: {
              id: true,
            },
          },

          salary: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
